<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-08-31T15:33:09 IST" name="Smoke Pack Suite" finished-at="2023-08-31T15:33:51 IST" duration-ms="41764">
    <groups>
    </groups>
    <test started-at="2023-08-31T15:33:09 IST" name="About_network_test" finished-at="2023-08-31T15:33:51 IST" duration-ms="41764">
      <class name="XGLT_15177_Test">
        <test-method is-config="true" signature="archive_old()[pri:0, instance:XGLT_15177_Test@51e4ccb3]" started-at="2023-08-31T15:33:09 IST" name="archive_old" finished-at="2023-08-31T15:33:09 IST" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- archive_old -->
        <test-method is-config="true" signature="initOR()[pri:0, instance:XGLT_15177_Test@51e4ccb3]" started-at="2023-08-31T15:33:09 IST" name="initOR" finished-at="2023-08-31T15:33:09 IST" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initOR -->
        <test-method is-config="true" signature="setupLog4j()[pri:0, instance:XGLT_15177_Test@51e4ccb3]" started-at="2023-08-31T15:33:09 IST" name="setupLog4j" finished-at="2023-08-31T15:33:09 IST" duration-ms="15" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupLog4j -->
        <test-method is-config="true" signature="login()[pri:0, instance:XGLT_15177_Test@51e4ccb3]" started-at="2023-08-31T15:33:09 IST" name="login" finished-at="2023-08-31T15:33:48 IST" duration-ms="38802" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="name(org.testng.ITestContext)[pri:0, instance:XGLT_15177_Test@51e4ccb3]" started-at="2023-08-31T15:33:48 IST" name="name" finished-at="2023-08-31T15:33:48 IST" duration-ms="2" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@61149fa5]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- name -->
        <test-method signature="About()[pri:2, instance:XGLT_15177_Test@51e4ccb3]" started-at="2023-08-31T15:33:48 IST" name="About" finished-at="2023-08-31T15:33:49 IST" duration-ms="1308" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [xGLinear 2.5.0] but found [xGLinear 2.6.0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [xGLinear 2.5.0] but found [xGLinear 2.6.0]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at XGLT_15177_Test.About(XGLT_15177_Test.java:34)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- About -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:XGLT_15177_Test@51e4ccb3]" started-at="2023-08-31T15:33:50 IST" name="closeBrowser" finished-at="2023-08-31T15:33:51 IST" duration-ms="1145" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- XGLT_15177_Test -->
    </test> <!-- About_network_test -->
  </suite> <!-- Smoke Pack Suite -->
</testng-results>
